services:

    kachkaev_counters.listener.counters_on_off:
        class: Kachkaev\CountersBundle\Listener\CountersOnOffListener
        arguments:
            - "%kachkaev_counters.on_off_trigger%"
            - "%kachkaev_counters.cookie%"
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    kachkaev_counters.twig.counters:
        class: Kachkaev\CountersBundle\Twig\CountersExtension
        arguments: ["@service_container"]
        tags:
            - { name: twig.extension }
